# Generated by Django 2.2 on 2019-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20190515_0913'),
        ('users', '0002_auto_20190427_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bookmarked_ads',
            field=models.ManyToManyField(to='ads.Advertisement'),
        ),
    ]
