# Generated by Django 2.2 on 2019-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20190515_0738'),
        ('users', '0003_auto_20190412_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bookmarked_ads',
            field=models.ManyToManyField(to='ads.Advertisement'),
        ),
    ]
