# Generated by Django 2.2 on 2019-06-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_bookmarked_ads'),
        ('users', '0004_member_bookmarked_ads'),
    ]

    operations = [
    ]
