# Generated by Django 2.2 on 2019-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(),
        ),
    ]
