# Generated by Django 2.2.1 on 2019-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_reportadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
