# Generated by Django 2.2 on 2019-06-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20190515_0738'),
        ('ads', '0003_reportadvertisement'),
    ]

    operations = [
    ]
