# Generated by Django 2.2 on 2019-06-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20190612_1111'),
        ('ads', '0004_merge_20190612_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='users.Member'),
            preserve_default=False,
        ),
    ]
