# Generated by Django 2.2 on 2019-06-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20190612_1240'),
        ('ads', '0005_auto_20190612_1305'),
    ]

    operations = [
    ]
